/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DailyAccuracy = IDL.Record({
  'date' : IDL.Text,
  'totalAttempts' : IDL.Nat,
  'accuracyPercent' : IDL.Nat,
});
export const Subject = IDL.Text;
export const AnalyticsSummary = IDL.Record({
  'dailyAccuracyLast7Days' : IDL.Vec(DailyAccuracy),
  'totalStudyHoursThisWeek' : IDL.Nat,
  'accuracyPerSubject' : IDL.Vec(IDL.Tuple(Subject, IDL.Nat)),
  'weeklyStudyMinutesPerDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const MessageRole = IDL.Variant({
  'mentor' : IDL.Null,
  'user' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const DashboardStats = IDL.Record({
  'totalStudyHoursThisWeek' : IDL.Nat,
  'todayCompletionPercent' : IDL.Nat,
  'weakSubjects' : IDL.Vec(Subject),
  'overallAccuracyPercent' : IDL.Nat,
});
export const LectureCard = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'channelTitle' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'viewCount' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const SubjectAccuracy = IDL.Record({
  'subject' : Subject,
  'correctAttempts' : IDL.Nat,
  'totalAttempts' : IDL.Nat,
  'accuracyPercent' : IDL.Nat,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'skipped' : IDL.Null,
  'completed' : IDL.Null,
});
export const TodayTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'topic' : IDL.Text,
  'subject' : Subject,
  'estimatedMinutes' : IDL.Nat,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ScheduledTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'topic' : IDL.Text,
  'subject' : Subject,
  'priority' : Priority,
  'dayIndex' : IDL.Nat,
  'rescheduledFromDay' : IDL.Opt(IDL.Nat),
  'estimatedMinutes' : IDL.Nat,
});
export const WeeklyTimetable = IDL.Record({
  'tasks' : IDL.Vec(ScheduledTask),
  'weekStartTimestamp' : Timestamp,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'year' : IDL.Nat,
  'questionText' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'clearChatHistory' : IDL.Func([], [], []),
  'getAdminConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'groqConfigured' : IDL.Bool,
          'youtubeConfigured' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLectureCards' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(LectureCard)],
      [],
    ),
  'getSubjectAccuracy' : IDL.Func([], [IDL.Vec(SubjectAccuracy)], ['query']),
  'getTodayTasks' : IDL.Func([], [IDL.Vec(TodayTask)], ['query']),
  'getWeeklyTimetable' : IDL.Func([], [WeeklyTimetable], []),
  'listQuestions' : IDL.Func(
      [IDL.Opt(Subject), IDL.Opt(Difficulty)],
      [IDL.Vec(Question)],
      [],
    ),
  'markTask' : IDL.Func([IDL.Nat, TaskStatus], [IDL.Bool], []),
  'rescheduleSkipped' : IDL.Func([], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], []),
  'setGroqApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setYoutubeApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DailyAccuracy = IDL.Record({
    'date' : IDL.Text,
    'totalAttempts' : IDL.Nat,
    'accuracyPercent' : IDL.Nat,
  });
  const Subject = IDL.Text;
  const AnalyticsSummary = IDL.Record({
    'dailyAccuracyLast7Days' : IDL.Vec(DailyAccuracy),
    'totalStudyHoursThisWeek' : IDL.Nat,
    'accuracyPerSubject' : IDL.Vec(IDL.Tuple(Subject, IDL.Nat)),
    'weeklyStudyMinutesPerDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const MessageRole = IDL.Variant({ 'mentor' : IDL.Null, 'user' : IDL.Null });
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const DashboardStats = IDL.Record({
    'totalStudyHoursThisWeek' : IDL.Nat,
    'todayCompletionPercent' : IDL.Nat,
    'weakSubjects' : IDL.Vec(Subject),
    'overallAccuracyPercent' : IDL.Nat,
  });
  const LectureCard = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'channelTitle' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'viewCount' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const SubjectAccuracy = IDL.Record({
    'subject' : Subject,
    'correctAttempts' : IDL.Nat,
    'totalAttempts' : IDL.Nat,
    'accuracyPercent' : IDL.Nat,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'skipped' : IDL.Null,
    'completed' : IDL.Null,
  });
  const TodayTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'topic' : IDL.Text,
    'subject' : Subject,
    'estimatedMinutes' : IDL.Nat,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ScheduledTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'topic' : IDL.Text,
    'subject' : Subject,
    'priority' : Priority,
    'dayIndex' : IDL.Nat,
    'rescheduledFromDay' : IDL.Opt(IDL.Nat),
    'estimatedMinutes' : IDL.Nat,
  });
  const WeeklyTimetable = IDL.Record({
    'tasks' : IDL.Vec(ScheduledTask),
    'weekStartTimestamp' : Timestamp,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'subject' : Subject,
    'difficulty' : Difficulty,
    'year' : IDL.Nat,
    'questionText' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'clearChatHistory' : IDL.Func([], [], []),
    'getAdminConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'groqConfigured' : IDL.Bool,
            'youtubeConfigured' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLectureCards' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(LectureCard)],
        [],
      ),
    'getSubjectAccuracy' : IDL.Func([], [IDL.Vec(SubjectAccuracy)], ['query']),
    'getTodayTasks' : IDL.Func([], [IDL.Vec(TodayTask)], ['query']),
    'getWeeklyTimetable' : IDL.Func([], [WeeklyTimetable], []),
    'listQuestions' : IDL.Func(
        [IDL.Opt(Subject), IDL.Opt(Difficulty)],
        [IDL.Vec(Question)],
        [],
      ),
    'markTask' : IDL.Func([IDL.Nat, TaskStatus], [IDL.Bool], []),
    'rescheduleSkipped' : IDL.Func([], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], []),
    'setGroqApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setYoutubeApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };