/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'dailyAccuracyLast7Days' : Array<DailyAccuracy>,
  'totalStudyHoursThisWeek' : bigint,
  'accuracyPerSubject' : Array<[Subject, bigint]>,
  'weeklyStudyMinutesPerDay' : Array<[string, bigint]>,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Timestamp,
}
export interface DailyAccuracy {
  'date' : string,
  'totalAttempts' : bigint,
  'accuracyPercent' : bigint,
}
export interface DashboardStats {
  'totalStudyHoursThisWeek' : bigint,
  'todayCompletionPercent' : bigint,
  'weakSubjects' : Array<Subject>,
  'overallAccuracyPercent' : bigint,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface LectureCard {
  'id' : string,
  'title' : string,
  'duration' : string,
  'channelTitle' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'viewCount' : string,
  'videoUrl' : string,
}
export type MessageRole = { 'mentor' : null } |
  { 'user' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Question {
  'id' : bigint,
  'topic' : string,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'year' : bigint,
  'questionText' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface ScheduledTask {
  'id' : bigint,
  'status' : TaskStatus,
  'topic' : string,
  'subject' : Subject,
  'priority' : Priority,
  'dayIndex' : bigint,
  'rescheduledFromDay' : [] | [bigint],
  'estimatedMinutes' : bigint,
}
export type Subject = string;
export interface SubjectAccuracy {
  'subject' : Subject,
  'correctAttempts' : bigint,
  'totalAttempts' : bigint,
  'accuracyPercent' : bigint,
}
export type TaskStatus = { 'pending' : null } |
  { 'skipped' : null } |
  { 'completed' : null };
export type Timestamp = bigint;
export interface TodayTask {
  'id' : bigint,
  'status' : TaskStatus,
  'topic' : string,
  'subject' : Subject,
  'estimatedMinutes' : bigint,
}
export interface WeeklyTimetable {
  'tasks' : Array<ScheduledTask>,
  'weekStartTimestamp' : Timestamp,
}
export interface _SERVICE {
  'clearChatHistory' : ActorMethod<[], undefined>,
  'getAdminConfig' : ActorMethod<
    [],
    { 'groqConfigured' : boolean, 'youtubeConfigured' : boolean }
  >,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLectureCards' : ActorMethod<[string, [] | [string]], Array<LectureCard>>,
  'getSubjectAccuracy' : ActorMethod<[], Array<SubjectAccuracy>>,
  'getTodayTasks' : ActorMethod<[], Array<TodayTask>>,
  'getWeeklyTimetable' : ActorMethod<[], WeeklyTimetable>,
  'listQuestions' : ActorMethod<
    [[] | [Subject], [] | [Difficulty]],
    Array<Question>
  >,
  'markTask' : ActorMethod<[bigint, TaskStatus], boolean>,
  'rescheduleSkipped' : ActorMethod<[], undefined>,
  'sendChatMessage' : ActorMethod<[string], Array<ChatMessage>>,
  'setGroqApiKey' : ActorMethod<[string], boolean>,
  'setYoutubeApiKey' : ActorMethod<[string], boolean>,
  'submitAnswer' : ActorMethod<[bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];