/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface WeeklyTimetable {
    tasks: Array<ScheduledTask>;
    weekStartTimestamp: Timestamp;
}
export interface DailyAccuracy {
    date: string;
    totalAttempts: bigint;
    accuracyPercent: bigint;
}
export interface AnalyticsSummary {
    dailyAccuracyLast7Days: Array<DailyAccuracy>;
    totalStudyHoursThisWeek: bigint;
    accuracyPerSubject: Array<[Subject, bigint]>;
    weeklyStudyMinutesPerDay: Array<[string, bigint]>;
}
export interface TodayTask {
    id: bigint;
    status: TaskStatus;
    topic: string;
    subject: Subject;
    estimatedMinutes: bigint;
}
export interface DashboardStats {
    totalStudyHoursThisWeek: bigint;
    todayCompletionPercent: bigint;
    weakSubjects: Array<Subject>;
    overallAccuracyPercent: bigint;
}
export interface LectureCard {
    id: string;
    title: string;
    duration: string;
    channelTitle: string;
    thumbnailUrl: string;
    description: string;
    viewCount: string;
    videoUrl: string;
}
export interface SubjectAccuracy {
    subject: Subject;
    correctAttempts: bigint;
    totalAttempts: bigint;
    accuracyPercent: bigint;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    role: MessageRole;
    timestamp: Timestamp;
}
export interface ScheduledTask {
    id: bigint;
    status: TaskStatus;
    topic: string;
    subject: Subject;
    priority: Priority;
    dayIndex: bigint;
    rescheduledFromDay?: bigint;
    estimatedMinutes: bigint;
}
export interface Question {
    id: bigint;
    topic: string;
    subject: Subject;
    difficulty: Difficulty;
    year: bigint;
    questionText: string;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export type Subject = string;
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum MessageRole {
    mentor = "mentor",
    user = "user"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaskStatus {
    pending = "pending",
    skipped = "skipped",
    completed = "completed"
}
export interface backendInterface {
    clearChatHistory(): Promise<void>;
    getAdminConfig(): Promise<{
        groqConfigured: boolean;
        youtubeConfigured: boolean;
    }>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getDashboardStats(): Promise<DashboardStats>;
    getLectureCards(subject: string, searchQuery: string | null): Promise<Array<LectureCard>>;
    getSubjectAccuracy(): Promise<Array<SubjectAccuracy>>;
    getTodayTasks(): Promise<Array<TodayTask>>;
    getWeeklyTimetable(): Promise<WeeklyTimetable>;
    listQuestions(subject: Subject | null, difficulty: Difficulty | null): Promise<Array<Question>>;
    markTask(taskId: bigint, status: TaskStatus): Promise<boolean>;
    rescheduleSkipped(): Promise<void>;
    sendChatMessage(text: string): Promise<Array<ChatMessage>>;
    setGroqApiKey(key: string): Promise<boolean>;
    setYoutubeApiKey(key: string): Promise<boolean>;
    submitAnswer(questionId: bigint, selectedOptionIndex: bigint): Promise<boolean>;
}
import type { ChatMessage as _ChatMessage, Difficulty as _Difficulty, MessageRole as _MessageRole, Priority as _Priority, Question as _Question, ScheduledTask as _ScheduledTask, Subject as _Subject, TaskStatus as _TaskStatus, Timestamp as _Timestamp, TodayTask as _TodayTask, WeeklyTimetable as _WeeklyTimetable } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async getAdminConfig(): Promise<{
        groqConfigured: boolean;
        youtubeConfigured: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminConfig();
            return result;
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLectureCards(arg0: string, arg1: string | null): Promise<Array<LectureCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLectureCards(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLectureCards(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getSubjectAccuracy(): Promise<Array<SubjectAccuracy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectAccuracy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectAccuracy();
            return result;
        }
    }
    async getTodayTasks(): Promise<Array<TodayTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayTasks();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayTasks();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyTimetable(): Promise<WeeklyTimetable> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyTimetable();
                return from_candid_WeeklyTimetable_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyTimetable();
            return from_candid_WeeklyTimetable_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuestions(arg0: Subject | null, arg1: Difficulty | null): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestions(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestions(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTask(arg0: bigint, arg1: TaskStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markTask(arg0, to_candid_TaskStatus_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTask(arg0, to_candid_TaskStatus_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async rescheduleSkipped(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleSkipped();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleSkipped();
            return result;
        }
    }
    async sendChatMessage(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGroqApiKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setGroqApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGroqApiKey(arg0);
            return result;
        }
    }
    async setYoutubeApiKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setYoutubeApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setYoutubeApiKey(arg0);
            return result;
        }
    }
    async submitAnswer(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChatMessage_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ScheduledTask_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScheduledTask): ScheduledTask {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TodayTask_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TodayTask): TodayTask {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyTimetable_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyTimetable): WeeklyTimetable {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_ScheduledTask>;
    weekStartTimestamp: _Timestamp;
}): {
    tasks: Array<ScheduledTask>;
    weekStartTimestamp: Timestamp;
} {
    return {
        tasks: from_candid_vec_n14(_uploadFile, _downloadFile, value.tasks),
        weekStartTimestamp: value.weekStartTimestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    topic: string;
    subject: _Subject;
    priority: _Priority;
    dayIndex: bigint;
    rescheduledFromDay: [] | [bigint];
    estimatedMinutes: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    topic: string;
    subject: Subject;
    priority: Priority;
    dayIndex: bigint;
    rescheduledFromDay?: bigint;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n10(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        subject: value.subject,
        priority: from_candid_Priority_n17(_uploadFile, _downloadFile, value.priority),
        dayIndex: value.dayIndex,
        rescheduledFromDay: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.rescheduledFromDay)),
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    subject: _Subject;
    difficulty: _Difficulty;
    year: bigint;
    questionText: string;
    correctOptionIndex: bigint;
    options: Array<string>;
}): {
    id: bigint;
    topic: string;
    subject: Subject;
    difficulty: Difficulty;
    year: bigint;
    questionText: string;
    correctOptionIndex: bigint;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        subject: value.subject,
        difficulty: from_candid_Difficulty_n27(_uploadFile, _downloadFile, value.difficulty),
        year: value.year,
        questionText: value.questionText,
        correctOptionIndex: value.correctOptionIndex,
        options: value.options
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    role: _MessageRole;
    timestamp: _Timestamp;
}): {
    id: bigint;
    content: string;
    role: MessageRole;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_MessageRole_n4(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    topic: string;
    subject: _Subject;
    estimatedMinutes: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    topic: string;
    subject: Subject;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n10(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        subject: value.subject,
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    skipped: null;
} | {
    completed: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "skipped" in value ? TaskStatus.skipped : "completed" in value ? TaskStatus.completed : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mentor: null;
} | {
    user: null;
}): MessageRole {
    return "mentor" in value ? MessageRole.mentor : "user" in value ? MessageRole.user : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScheduledTask>): Array<ScheduledTask> {
    return value.map((x)=>from_candid_ScheduledTask_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TodayTask>): Array<TodayTask> {
    return value.map((x)=>from_candid_TodayTask_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject | null): [] | [_Subject] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty | null): [] | [_Difficulty] {
    return value === null ? candid_none() : candid_some(to_candid_Difficulty_n22(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    skipped: null;
} | {
    completed: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.skipped ? {
        skipped: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
